### PR TITLE
added fast minimum_distance calculation to UnbindingBC.  

### PR DESCRIPTION
**Pull request by alexrd**
Note: requires the function "minimum_distance" from geomm.distance  

This also removes the mdtraj dependency (as well as the need to specify a topology at all) from  UnbindingBC.

### CODE REVIEW

**Comment by salotz-sitx** [comment]
We need to add the `minimum_distance` to geomm first right?

**Comment by alexrd** [comment]
Yes it does.  I think there is a PR over there as well.

**Comment by salotz-sitx** [comment]
I ask because I don't see one :)

**Comment by alexrd** [comment]
14 months later... turns out the merge request was on gitlab.  Just put one on github as well!

**Review by SamikBose — APPROVED** [review]

**Pull request merged**
